name: SPICE Build

on:
  workflow_dispatch:
  
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  BUILD_TYPE: Release
  CTEST_OUTPUT_ON_FAILURE: 1
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

jobs:
  build-windows:
    name: "windows-${{matrix.platform}}"
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ x64 ]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v6
      with:
        submodules: true

    - name: Update vcpkg
      shell: pwsh
      run: |
        $vcpkgCommit = 'c3867e714dd3a51c272826eea77267876517ed99'
        pushd "$env:VCPKG_INSTALLATION_ROOT"
        git fetch origin $vcpkgCommit
        git reset --hard $vcpkgCommit
        ./bootstrap-vcpkg.bat
        ./vcpkg.exe integrate install
        popd

    - name: Setup NuGet Credentials
      shell: pwsh
      run: |
        $nugetCmd = vcpkg fetch nuget | Select-Object -Last 1
        $nugetSource = 'https://nuget.pkg.github.com/CelestiaProject/index.json'
        & "$nugetCmd" sources add `
          -Source "$nugetSource" `
          -StorePasswordInClearText `
          -Name "GitHub" `
          -Username 'CelestiaProject' `
          -Password '${{secrets.GITHUB_TOKEN}}'

    - name: Install dependencies
      shell: pwsh
      run: |
        $packages = @(
          'boost-container',
          'boost-container-hash',
          'boost-smart-ptr',
          'cspice',
          'eigen3',
          'ffmpeg[core,avcodec,avformat,gpl,swscale,x264]',
          'fmt',
          'freetype',
          'gettext[tools]',
          'gperf',
          'libepoxy',
          'libjpeg-turbo',
          'libpng',
          'luajit',
          'qtbase[core,opengl,widgets,freetype,harfbuzz,jpeg,png]'
        )

        # We treat x86 builds as native, other builds keep host as x64-windows.
        # Currently this is equivalent to the platform triplet, but this would
        # differ if we enable arm64-windows builds in future

        if ( '${{matrix.platform}}' -eq 'x86' ) {
          $hostTriplet = 'x86-windows-release'
        } else {
          $hostTriplet = 'x64-windows-release'
        }

        pushd "$env:VCPKG_INSTALLATION_ROOT"
        ./vcpkg.exe --overlay-triplets=${{github.workspace}}/windows/vcpkg-triplets `
                    --triplet=${{matrix.platform}}-windows-release `
                    --host-triplet=$hostTriplet `
                    install --recurse @packages
        popd

    - name: Configure CMake
      shell: pwsh
      run: |
        if ( '${{matrix.platform}}' -eq 'x86' ) {
            $GeneratorPlatform = 'Win32'
        } else {
            $GeneratorPlatform = '${{matrix.platform}}'
        }

        cmake -B '${{github.workspace}}/build' `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" `
            -DVCPKG_OVERLAY_TRIPLETS="${{github.workspace}}/windows/vcpkg-triplets" `
            -DVCPKG_TARGET_TRIPLET=${{matrix.platform}}-windows-release `
            -DCMAKE_GENERATOR_PLATFORM="$GeneratorPlatform" `
            -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/install" `
            -DENABLE_SPICE=ON    `
            -DENABLE_TOOLS=ON     `
            -DENABLE_TESTS=ON     `
            -DENABLE_SDL=OFF      `
            -DENABLE_QT5=OFF      `
            -DENABLE_WIN=ON       `
            -DENABLE_QT6=ON       `
            -DENABLE_FFMPEG=ON    `
            -DENABLE_MINIAUDIO=ON `
            -DENABLE_LTO=ON       `
            -DUSE_ICU=ON          `
            -DUSE_WIN_ICU=ON

    - name: Build
      shell: pwsh
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} '--' /maxcpucount:2 /nologo

    - name: Test
      shell: pwsh
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Install Windows
      shell: pwsh
      run: |
        cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --component core
        cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --component wingui
        Rename-Item -Path "install" -NewName "install-wingui"

    - name: Upload Windows GUI
      uses: actions/upload-artifact@v5
      if: success()
      with:
        name: celestia-windows-${{matrix.platform}}-wingui
        if-no-files-found: error
        path: |
          ${{github.workspace}}/install-wingui/

    - name: Install Qt6
      shell: pwsh
      run: |
        cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --component core
        cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --component qt6gui
        Rename-Item -Path "install" -NewName "install-qt6gui"

    - name: Upload Qt6 GUI
      uses: actions/upload-artifact@v5
      if: success()
      with:
        name: celestia-windows-${{matrix.platform}}-qt6gui
        if-no-files-found: error
        path: |
          ${{github.workspace}}/install-qt6gui/

    - name: Install tools
      shell: pwsh
      run: |
        cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --component tools
        Rename-Item -Path "install" -NewName "install-tools"

    - name: Upload tools
      uses: actions/upload-artifact@v5
      if: success()
      with:
        name: celestia-windows-${{matrix.platform}}-tools
        if-no-files-found: error
        path: |
          ${{github.workspace}}/install-tools/
